// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCQLDFlw7gNEao8kRMnRNR_4of2gRo7lR8',
    appId: '1:416537953878:web:2bf9d953f02f8a588a5df7',
    messagingSenderId: '416537953878',
    projectId: 'halaph-8a811',
    authDomain: 'halaph-8a811.firebaseapp.com',
    storageBucket: 'halaph-8a811.firebasestorage.app',
    measurementId: 'G-RCLD1CY8GN',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBpWbnPqXrlEEc2Vt5IDTBcOiX_eLjBO2s',
    appId: '1:416537953878:android:d3baf6ab846b760c8a5df7',
    messagingSenderId: '416537953878',
    projectId: 'halaph-d4eaa',
    storageBucket: 'halaph-d4eaa.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCq-d6Z31tQmy20hjqfi5FH2cSJ8ODBCpY',
    appId: '1:416537953878:ios:f97984acd7592e048a5df7',
    messagingSenderId: '416537953878',
    projectId: 'halaph-d4eaa',
    storageBucket: 'halaph-d4eaa.firebasestorage.app',
    iosBundleId: 'com.halaph.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCq-d6Z31tQmy20hjqfi5FH2cSJ8ODBCpY',
    appId: '1:416537953878:ios:f97984acd7592e048a5df7',
    messagingSenderId: '416537953878',
    projectId: 'halaph-d4eaa',
    storageBucket: 'halaph-d4eaa.firebasestorage.app',
    iosBundleId: 'com.example.halaph',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCQLDFlw7gNEao8kRMnRNR_4of2gRo7lR8',
    appId: '1:416537953878:web:aeb672d1653e12528a5df7',
    messagingSenderId: '416537953878',
    projectId: 'halaph-8a811',
    authDomain: 'halaph-8a811.firebaseapp.com',
    storageBucket: 'halaph-8a811.firebasestorage.app',
    measurementId: 'G-02EK4PG2VP',
  );
}
